name: CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      # Obtener el código fuente del repositorio
      - uses: actions/checkout@v4
      # Configurar la versión de Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      # Instalar las dependencias del proyecto
      - name: Install Dependencies
        run: npm install 
      # Verificación de estilo de código con ESLint
      - name: Anàlisi amb ESLint
        run: npm run lint
      # Construcción o build del proyecto
      - name: Build del projecte
        run: npm run build
      # Execució de tests unitaris
      - name: Run test
        run: npm test
      # Desplegament automàtic a Render (només si els tests passen i estem a main)
      - name: Desplegament a Render
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Tests passats amb èxit. Iniciant desplegament a Render..."
          curl -X POST https://api.render.com/deploy/srv-d7gelsrbc2fs73dhr68g?key=qWk2Z2dn8GA